### PR TITLE
add portal_scraper to travis

### PR DESCRIPTION
**Pull request by tymoyato**

### CODE REVIEW

**Comment by tymoyato** [comment]
[add portal_scraper to travis](https://trello.com/c/qcdQKHVc/1008-add-portalscraper-to-travis)

**Comment by armandmgt** [comment]
Add a dev dependency to `rubocop-rspec` for the build to pass 😉

**Comment by tymoyato** [comment]
> rubocop-rspec

Yes @armandmgt thanks you 🏆

**Comment by tymoyato** [comment]
https://github.com/rubocop-hq/rubocop/issues/6398#issuecomment-431901995

**Pull request merged**
